### ISSUE TITLE
Ajouter un model de Demande terminé

### ISSUE THREAD

**Issue by KBjeanelie** [gloirebeniche/oppuss#7]
Cette tâche consiste a représenter un modèle  de demande déjà clôturer qui sera dans une liste. Ainsi le client pourra avoir une liste des ses demande qu'il a déjà fait et avoir même la possibilité de refaire la demande

**Comment by gloirebeniche** [comment]
j'ai à nouveau customiser la cardView

**Comment by gloirebeniche** [comment]
ok
